# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 05989d5fd1e8c263597b7db16cda529e280e3de33589ab84ed78f77fc1c3cca4a7c1006ebec5a8ca689a0f23ba3240eda5f2e86da752876efaa4c9bc8066ac2a

test:
  secret_key_base: 745dc369794fcf735493580d1a535f0c374dedfa1011d2021959061cebeb4ede2e73b70cdecaf2581ccd076396d61e5d78c9fdad948c202174f2e662c0f80518

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
